### ISSUE TITLE
Initial Setup Ui

### ISSUE THREAD

**Issue by sabuto** [artdevgame/shots-fired-support#13]
On the initial setup ui, there is a button for settings next to the minimise. This should not be visible as clicking the button takes you nowhere (i assume the initial setup is the settings menu) :)

**Comment by ministerofpanic** [comment]
Hey @Sabuto,

Thanks for creating this issue and for using Shots Fired. I'm currently working on the next version of the app, so I probably won't change anything in the current version, but I'm grateful for your input.
