### ISSUE TITLE
Trigger Events In Nested Scene

### ISSUE THREAD

**Issue by ss44** [artdevgame/shots-fired-support#20]
Nested scenes are useful at organizing alerts of various kinds and services which can then appear across multiple parent scenes.

Currently, when triggering an action this plugin switches to a scene and then executes w/e action on the item.

Ideally, it would be nice if could select an action that occurs within a nested scene without having to switch to that nested scene within OBS.

Example OBS setup:

Game Scene
- ShotsFiredNestedScene

ShotsFiredNestedScene
- Goal: MediaSource 

Shots Fired: 
Being able to select Goal from ShotsFiredNestedScene, but select the Goal media source.

I would think all the current logic can remain the same but have a checkbox when adding an action in the select scene drop-down that prevents switching to the scene but still acting on w/e elements are available there.

**Comment by ministerofpanic** [comment]
Hey @ss44 

I'm not very familiar with the kind of setup you're describing. Is there anyway to expand on what you're trying to do with some screenshots?

> without having to switch to that nested scene within OBS

I think this could be a problem with the underlying technology (I don't think it's possible to alter items without changing to the scene first) but would have to check.
