### ISSUE TITLE
Ability to modify POST payload

### ISSUE THREAD

**Issue by ss44** [artdevgame/shots-fired-support#21]
Any chance you could add support (premium) for customizing the payload on post request.

The desired use case here is integrating with streamerbot which runs an integrated server but requires the post body to specify an action to trigger.

**Comment by ministerofpanic** [comment]
Hey @ss44 👋🏻 
We spoke about this in Discord but thought I'd answer here too incase others stumble across it.
I'm currently working on v6 of Shots Fired and quite far in to the development of it, I'll add the feature you've requested to that -thanks for the suggestion!
