### ISSUE TITLE
A random possibility of it happening?

### ISSUE THREAD

**Issue by Jonikalus** [artdevgame/shots-fired-support#7]
Add it so you can set it only to happen at 5% of the kills or something like that.

**Comment by ministerofpanic** [comment]
There will be 2 ways to achieve this in the next version:
1. Change the probability to a number between 1-100%, the program will decide whether to trigger the sequence or not
2. Add a filter and program the probability yourself

![image](https://user-images.githubusercontent.com/353729/139573969-42421882-2880-4373-8a05-8ee261d50e38.png)
