### ISSUE TITLE
Can't select individual sources

### ISSUE THREAD

**Issue by Jonikalus** [artdevgame/shots-fired-support#8]
I can only select all on none and if I type in a delay or a duration it sets the same duration on everything. I even paid for your subscription and it is not working.

**Comment by ministerofpanic** [comment]
Hey @Jonikalus 

Thanks for your support via the subscription.

I apologise that you're having problems with it. If you can help me understand the problems a little more I'd be more than happy to get them addressed.

1. I can't replicate: "if I type in a delay or a duration it sets the same duration on everything", so I need a bit more info on what steps you're taking to help me understand.

2. "I can only select all or none" - If you could help me understand this too please. If you're trying to get the item to disappear, the duration must be greater than 0. I.e. If you want some text to appear temporarily, have it set to 'on' first and then give it a duration of 1 second to make it disappear after that time passes.

Here's a video I've recorded this morning using the downloaded version of my app from Overwolf, it demonstates the behaviour I'm seeing, let me know if this is different to what you're experiencing:
https://youtu.be/glrEjNdIsoo

**Comment by Jonikalus** [comment]
https://youtu.be/BOccPQDCRrU This should show the basics of my issue.

Also thank you for the response.

**Comment by ministerofpanic** [comment]
Thanks for taking the time to record that @Jonikalus, that's really weird!

I've got a new version that I'd put on hold for a while, would you be interested in testing it for me to see if the same behaviour occurs?

If so, I've created a Discord channel you could hop into and I can transfer the relevant file via that: https://discord.gg/eBBnNfM

If not, I'll try and get it released asap so it'll be available through the Overwolf store.

**Comment by ministerofpanic** [comment]
Marking this as resolved, we tested this via Discord on v4.0.0 and that seems to have resolved the issue.
