### ISSUE TITLE
Event descriptions

### ISSUE THREAD

**Issue by Jonikalus** [artdevgame/shots-fired-support#9]
Add a description of what each effect is. Some have really similar names so it is hard to understand what they do sometimes.
Would be nice to just have a box pop up when u hover over them.

**Comment by ministerofpanic** [comment]
Done some groundwork to getting this implemented in the next version. I'm going to take another look at the UI soon to see how to plug them in.

**Comment by ministerofpanic** [comment]
Built a tool that will fetch the description from Overwolf docs, but might need to go back and make these better in the future
![image](https://user-images.githubusercontent.com/353729/139573833-f382971c-48ad-4b62-9ddf-288b33f10d7c.png)
